feat: non-inclusion proofs for identities and contracts
dashevo/js-drive pull request #551
Opened 2021-07-30 16:34 UTC by antouhou

## Issue being fixed or feature implemented

Non-inclusion (absence) proofs for identities and data contracts

## What was done?

- Removed all errors and filtering that were causing
- Fixed a bug in the `getIdentityIdsByPublicKeyHashes` that was resulting in the 

## How Has This Been Tested?

With test suite (TODO: add a link to test suite PR)

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2021-08-09 16:36 UTC, shumkov requested changes

2021-08-09 16:36 UTC, shumkov commented on lib/abci/handlers/query/identitiesByPublicKeyHashesQueryHandlerFactory.js
> +      storeTreeProofs.setPublicKeyHashesToIdentityIdsProof(publicKeyStoreTreeProof);
We don't need to pass the whole proofs actually. We can pass `PublicKeyHashesToIdentityIds` only for non-existing proof and `IdentitiesProof` only for existing @antouhou

2021-08-13 13:07 UTC, shuplenkov approved these changes

2021-08-13 13:35 UTC, shumkov approved these changes
LGTM! ❤️

2021-08-13 13:35 UTC, merged